"""Independent local scientific recomputation probe for the frozen Manavgat result.

WHAT THIS IS -- AND HOW IT DIFFERS FROM THE REPLAY
--------------------------------------------------
`reference_replay.py` proved that the regional WRAPPER preserves the frozen
Manavgat science: it reused the frozen `model/` and `compare/` artefacts and
compared the wrapper's projection of them against the originals.

This module answers a different question:

    re-running the fit and the comparison for real, from the frozen local
    inputs, does the SAME science come out?

So here the frozen `model/` and `compare/` trees are NEVER copied. They are
regenerated by the production stage functions:

* ``run_model_stage``   -- common cohort, shared spatial folds, 30 random-forest
                           fits, out-of-fold predictions, point metrics, thermal
                           contributions, and ONE paired spatial-block bootstrap
                           of 1000 draws.
* ``run_compare_stage`` -- every comparison table, the bootstrap evidence matrix
                           and the descriptive report.

Everything upstream of the fit is REUSED from the frozen tree (verified copy):
plan documents, the pre-label censor raster, the exported predictor rasters and
the whole local-downstream chain including the three Step8A datasets. No Earth
Engine call, no remote export and no download happens at any point.

WHY THE STAGE BINDING IS CONSTRUCTED RATHER THAN ASSERTED
---------------------------------------------------------
``run_analysis`` reaches the model stage through ``assert_model_binding``, which
requires every upstream provenance document to carry THIS run's ``analysis_id``
and to record paths inside THIS run's namespace. The frozen documents carry the
analysis id of the original run -- `compute_analysis_id` folds `git_commit` into
the identity, so a run today can never reproduce it -- and they record absolute
paths into the frozen namespace.

Making that assertion pass would mean rewriting the recorded `analysis_id` and
roughly 170 recorded artefact paths inside the frozen export-provenance
documents. Rewriting export provenance so that a verification passes would
destroy the very thing the probe is meant to establish, so it is NOT done.

Instead this module resolves `model_datasets` itself -- verifying each dataset
against the SHA-256 its own producing stage recorded -- and hands that binding
to the real, unmodified ``run_model_stage``. The compare binding then replicates
``assert_compare_binding``'s post-model block verbatim against the freshly
written model tree. The scientific code paths are the production ones; only the
provenance-identity assertions that cannot hold across analysis ids are
replaced by an explicit, hash-verified equivalent.

Design references
-----------------
src/window_closure_sensitivity.py:8996  run_model_stage
src/window_closure_sensitivity.py:10540 run_compare_stage
src/window_closure_sensitivity.py:9776  assert_compare_binding (replicated block)
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any, Mapping, Optional, Sequence

from src.multi_region_window_closure.contract import (
    MultiRegionWindowClosureError, REFERENCE_AOI, VARIANTS,
)
from src.multi_region_window_closure.reference_replay import (
    CLASS_FLOAT, CLASS_MATERIAL, CLASS_SCIENTIFIC, EXCLUDED_TREE_COMPONENT,
    FLOAT_SERIALIZATION_TOLERANCE, _numeric_diffs, frozen_manavgat_root,
    frozen_source_files, partition_frozen_source, sha256_path, tree_snapshot,
)

#: Temporary probe namespace. Distinct from the frozen namespace, from the
#: production regional namespace and from the replay namespace.
PROBE_DIAGNOSTIC_NAMESPACE = "window_closure_region_recompute_probe"

PROBE_MODE_ID = "manavgat_local_recomputation_probe.v1"

#: Frozen stages whose artefacts are REUSED (verified copy).
REUSED_FROZEN_STAGES: tuple[str, ...] = ("plan", "export", "local-downstream")

#: Frozen stages that are NEVER copied -- they are recomputed for real.
RECOMPUTED_STAGES: tuple[str, ...] = ("fit", "compare")

#: Top-level frozen sub-trees the probe must not contain before recomputation.
RECOMPUTED_TREES: tuple[str, ...] = ("model", "compare")


class RecomputeProbeError(MultiRegionWindowClosureError):
    """Fail-closed probe condition."""


def probe_output_root(output_root: Optional[Path] = None) -> Path:
    from core.paths import PROJECT_ROOT

    if output_root:
        return Path(output_root)
    return Path(PROJECT_ROOT) / "outputs" / "diagnostics" / PROBE_DIAGNOSTIC_NAMESPACE


def replay_namespace_root(output_root: Optional[Path] = None) -> Optional[Path]:
    """The regional replay namespace produced by the previous turn, if present."""
    from src.multi_region_window_closure.reference_replay import replay_output_root

    aoi_root = replay_output_root(output_root) / REFERENCE_AOI
    if not aoi_root.is_dir():
        return None
    candidates = sorted(
        path for path in aoi_root.glob("*")
        if path.is_dir() and not path.name.startswith("_")
    )
    return candidates[-1] if candidates else None


# =============================================================================
# Namespace materialization -- upstream only, never model/ or compare/
# =============================================================================
def materialize_upstream(frozen_source: Path, probe_root: Path) -> dict[str, Any]:
    """Copy every pre-fit frozen artefact into the probe, verifying each copy.

    `model/` and `compare/` are deliberately excluded: regenerating them is the
    whole point of the probe, and a copy would silently answer the question.
    """
    frozen_source, probe_root = Path(frozen_source), Path(probe_root)
    partition = partition_frozen_source(frozen_source)
    target_root = probe_root / REFERENCE_AOI
    records: list[dict[str, str]] = []
    for stage in REUSED_FROZEN_STAGES:
        for relative in partition[stage]:
            source = frozen_source / relative
            destination = target_root / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, destination)
            source_hash = sha256_path(source)
            if sha256_path(destination) != source_hash:
                raise RecomputeProbeError(
                    "BLOCKER: UPSTREAM_REUSE_HASH_MISMATCH -- "
                    f"{relative} did not copy byte-identically."
                )
            records.append({
                "stage": stage, "relative_path": str(relative),
                "sha256": source_hash, "size_bytes": str(source.stat().st_size),
            })
    excluded = sorted(
        str(relative) for stage in RECOMPUTED_STAGES for relative in partition[stage]
    )
    for tree in RECOMPUTED_TREES:
        if (target_root / tree).exists():
            raise RecomputeProbeError(
                f"BLOCKER: RECOMPUTED_TREE_PRESEEDED -- '{tree}/' exists in the "
                "probe before recomputation; the probe refuses to compare a copy "
                "against its own source."
            )
    return {
        "probe_root": str(probe_root),
        "experiment_root": str(target_root),
        "reused_stages": list(REUSED_FROZEN_STAGES),
        "reused_artifact_count": len(records),
        "reused_artifact_bytes": sum(int(r["size_bytes"]) for r in records),
        "reused_artifacts": records,
        "excluded_frozen_artifact_count": len(excluded),
        "excluded_frozen_artifacts": excluded,
        "recomputed_stages": list(RECOMPUTED_STAGES),
        "gee_queries_run": False,
        "gee_exports_run": False,
    }


# =============================================================================
# Bindings
# =============================================================================
def build_model_binding(
    *, experiment_id: str, variants: Sequence[Mapping[str, Any]],
    probe_root: Path, experiments_root: Optional[Path] = None,
) -> dict[str, Any]:
    """`model_datasets` resolved and hash-verified inside the probe namespace.

    Mirrors the dataset half of ``assert_model_binding``. Every shifted dataset
    is checked against the SHA-256 its own local-downstream metadata recorded,
    and the canonical Step8A is checked against the central frozen anchor, so a
    silently different input cannot reach the fit.
    """
    from src.multi_region_window_closure.inputs import CANONICAL_STEP8A_SHA256
    from src.window_closure_sensitivity import (
        CANONICAL_VARIANT_ID, canonical_step8a_path, canonical_step8a_stats_path,
        local_downstream_metadata_path, nonzero_variants,
        variant_step8a_dataset_path, variant_step8a_stats_path,
    )

    def _require(condition: bool, message: str) -> None:
        if not condition:
            raise RecomputeProbeError(f"BLOCKER: PROBE_MODEL_BINDING -- {message}")

    canonical_dataset = canonical_step8a_path(experiment_id, experiments_root)
    canonical_stats = canonical_step8a_stats_path(experiment_id, experiments_root)
    _require(canonical_dataset.is_file(), f"canonical Step8A missing at {canonical_dataset}.")
    _require(canonical_stats.is_file(), f"canonical Step8A stats missing at {canonical_stats}.")
    canonical_sha256 = sha256_path(canonical_dataset)
    _require(
        canonical_sha256 == CANONICAL_STEP8A_SHA256[experiment_id],
        f"canonical Step8A hashes {canonical_sha256}, central anchor is "
        f"{CANONICAL_STEP8A_SHA256[experiment_id]}.",
    )

    datasets: dict[str, dict[str, Any]] = {
        CANONICAL_VARIANT_ID: {
            "variant_id": CANONICAL_VARIANT_ID, "is_canonical": True,
            "dataset_path": str(canonical_dataset),
            "dataset_sha256": canonical_sha256,
            "stats_path": str(canonical_stats),
            "stats_sha256": sha256_path(canonical_stats),
            "source": "frozen canonical production Step8A (read-only)",
        },
    }
    pinned: set[Any] = set()
    for variant in nonzero_variants(list(variants)):
        variant_id = variant["variant_id"]
        metadata_path = local_downstream_metadata_path(experiment_id, variant_id, probe_root)
        _require(metadata_path.is_file(), f"'{variant_id}' local-downstream metadata missing.")
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        _require(metadata.get("status") == "pass",
                 f"'{variant_id}' local-downstream status is {metadata.get('status')!r}.")
        _require(metadata.get("experiment_id") == experiment_id,
                 f"'{variant_id}' local-downstream names another experiment.")
        _require(metadata.get("variant_id") == variant_id,
                 f"'{variant_id}' local-downstream names another variant.")
        dataset_path = variant_step8a_dataset_path(experiment_id, variant_id, probe_root)
        stats_path = variant_step8a_stats_path(experiment_id, variant_id, probe_root)
        _require(dataset_path.is_file(), f"'{variant_id}' Step8A missing at {dataset_path}.")
        _require(stats_path.is_file(), f"'{variant_id}' Step8A stats missing at {stats_path}.")
        digest = sha256_path(dataset_path)
        _require(
            digest == metadata.get("step8a_dataset_sha256"),
            f"'{variant_id}' Step8A hashes {digest} but its local-downstream "
            f"metadata recorded {metadata.get('step8a_dataset_sha256')!r}.",
        )
        _require(
            sha256_path(stats_path) == metadata.get("step8a_stats_sha256"),
            f"'{variant_id}' Step8A stats hash differs from its metadata.",
        )
        pinned.add(metadata.get("canonical_step8a_sha256"))
        datasets[variant_id] = {
            "variant_id": variant_id, "is_canonical": False,
            "shift_days": int(variant["shift_days"]),
            "dataset_path": str(dataset_path), "dataset_sha256": digest,
            "stats_path": str(stats_path), "stats_sha256": sha256_path(stats_path),
            "local_downstream_metadata_path": str(metadata_path),
            "local_downstream_metadata_sha256": sha256_path(metadata_path),
            "source": "window-closure local downstream (status=pass, reused frozen)",
        }
    _require(pinned == {canonical_sha256},
             f"local-downstream pinned canonical hash(es) {sorted(map(str, pinned))}.")
    _require(len(datasets) == len(VARIANTS),
             f"resolved {len(datasets)} datasets, expected {len(VARIANTS)}.")
    return {"model_datasets": datasets, "canonical_step8a_sha256": canonical_sha256}


def build_compare_binding(
    *, experiment_id: str, analysis_id: str, probe_root: Path,
    model_binding: Mapping[str, Any],
) -> dict[str, Any]:
    """Replicates the post-model block of ``assert_compare_binding`` verbatim."""
    from src.window_closure_sensitivity import (
        MODEL_FAMILIES, MODEL_METADATA_SCHEMA, MODEL_STAGE_REQUIRED_FLAGS,
        compare_variant_order, model_metadata_path, model_relative_layout,
        model_root, model_variant_oof_relpath, read_model_stage_metadata,
        sha256_file,
    )

    def _require(condition: bool, message: str) -> None:
        if not condition:
            raise RecomputeProbeError(f"BLOCKER: PROBE_COMPARE_BINDING -- {message}")

    metadata = read_model_stage_metadata(experiment_id, probe_root)
    metadata_path = model_metadata_path(experiment_id, probe_root)
    _require(metadata.get("schema_version") == MODEL_METADATA_SCHEMA,
             f"model schema is {metadata.get('schema_version')!r}.")
    _require(metadata.get("status") == "pass",
             f"model status is {metadata.get('status')!r}.")
    _require(metadata.get("analysis_id") == analysis_id, "model analysis_id mismatch.")
    _require(metadata.get("experiment_id") == experiment_id, "model experiment_id mismatch.")
    for flag, expected in MODEL_STAGE_REQUIRED_FLAGS.items():
        _require(metadata.get(flag) is expected,
                 f"model metadata {flag}={metadata.get(flag)!r}, expected {expected!r}.")

    root = model_root(experiment_id, probe_root)
    layout = model_relative_layout()
    required = [layout[key] for key in sorted(layout) if key != "metadata"]
    recorded = {
        str(record.get("relative_path")): record
        for record in (metadata.get("artifact_inventory") or [])
    }
    for relative in required:
        _require(relative in recorded, f"model metadata records no artefact for '{relative}'.")
    variant_ids = compare_variant_order(sorted(metadata.get("variant_ids") or []))
    for variant_id in variant_ids:
        for family in MODEL_FAMILIES:
            relative = model_variant_oof_relpath(variant_id, family)
            _require(relative in recorded, f"model metadata records no artefact for '{relative}'.")

    artifacts: dict[str, dict[str, Any]] = {}
    for relative, record in sorted(recorded.items()):
        path = Path(str(record.get("path") or ""))
        _require(path.is_file(), f"model artefact '{relative}' is missing at {path}.")
        digest = sha256_file(path)
        _require(digest == record.get("sha256"), f"model artefact '{relative}' hash mismatch.")
        _require(root in path.resolve().parents, f"model artefact '{relative}' lies outside {root}.")
        artifacts[relative] = {
            "relative_path": relative, "path": str(path), "sha256": digest,
            "bytes": int(path.stat().st_size),
        }
    return {
        **dict(model_binding),
        "bound_to_model": True,
        "model_stage_metadata": metadata,
        "model_stage_metadata_path": str(metadata_path),
        "model_stage_metadata_sha256": sha256_file(metadata_path),
        "model_artifacts": artifacts,
        "model_variant_ids": variant_ids,
    }


# =============================================================================
# The recomputation itself
# =============================================================================
def recompute_model_and_compare(
    *, frozen_source: Path, probe_root: Path, experiments_root: Optional[Path] = None,
) -> dict[str, Any]:
    """Really fit, really bootstrap, really rebuild the comparison tables."""
    from core.experiment_context import build_experiment_context
    from src.window_closure_sensitivity import (
        DEFAULT_SHIFTS, build_window_variants, canonical_window,
        compute_analysis_id, frozen_input_inventory, normalize_shifts,
        run_compare_stage, run_model_stage, scientific_configuration,
        common_prelabel_interval,
    )

    experiment_id = REFERENCE_AOI
    shifts = normalize_shifts(DEFAULT_SHIFTS)
    context = build_experiment_context(experiment_id)
    canonical = canonical_window(context)
    variants = build_window_variants(context, shifts)
    censor = common_prelabel_interval(variants)
    inventory = frozen_input_inventory(experiment_id, experiments_root, context)
    config = scientific_configuration(
        experiment_id, context, variants, censor, inventory, shifts,
    )
    analysis_id = compute_analysis_id(config)

    model_binding = build_model_binding(
        experiment_id=experiment_id, variants=variants, probe_root=probe_root,
        experiments_root=experiments_root,
    )
    model_outcome = run_model_stage(
        experiment_id, analysis_id, canonical, variants, model_binding,
        output_root=probe_root, experiments_root=experiments_root,
        force=False, resume=False,
    )
    if model_outcome.get("reused"):
        raise RecomputeProbeError(
            "BLOCKER: MODEL_STAGE_WAS_REUSED -- the probe must fit, not reuse."
        )
    compare_binding = build_compare_binding(
        experiment_id=experiment_id, analysis_id=analysis_id,
        probe_root=probe_root, model_binding=model_binding,
    )
    compare_outcome = run_compare_stage(
        experiment_id, analysis_id, variants, compare_binding,
        output_root=probe_root, experiments_root=experiments_root,
        force=False, resume=False,
    )
    if compare_outcome.get("reused"):
        raise RecomputeProbeError(
            "BLOCKER: COMPARE_STAGE_WAS_REUSED -- the probe must rebuild, not reuse."
        )
    metadata = model_outcome["metadata"]
    return {
        "analysis_id": analysis_id,
        "experiment_id": experiment_id,
        "model_fit": bool(metadata.get("model_fit")),
        "bootstrap_run": bool(metadata.get("bootstrap_run")),
        "model_evaluation_count": metadata.get("model_evaluation_count"),
        "model_files_written": len(model_outcome.get("files_written", [])),
        "compare_files_written": len(compare_outcome.get("files_written", [])),
        "model_reused": bool(model_outcome.get("reused")),
        "compare_reused": bool(compare_outcome.get("reused")),
        "model_configuration": metadata.get("model_configuration"),
        "gee_queries_run": False,
        "gee_exports_run": False,
    }


def summarize_existing_probe(
    *, frozen_source: Path, probe_root: Path,
) -> tuple[dict[str, Any], dict[str, Any]]:
    """Re-derive the materialization/recomputation summaries, read-only.

    Used by `--report-only` so the comparison can be rebuilt without refitting.
    Both summaries are read back from what the earlier run actually persisted,
    never assumed.
    """
    frozen_source, probe_root = Path(frozen_source), Path(probe_root)
    experiment_root = probe_root / REFERENCE_AOI
    partition = partition_frozen_source(frozen_source)
    reused = [rel for stage in REUSED_FROZEN_STAGES for rel in partition[stage]]
    excluded = sorted(
        str(rel) for stage in RECOMPUTED_STAGES for rel in partition[stage]
    )
    present = [rel for rel in reused if (experiment_root / rel).is_file()]
    if len(present) != len(reused):
        raise RecomputeProbeError(
            "BLOCKER: PROBE_UPSTREAM_INCOMPLETE -- "
            f"{len(reused) - len(present)} reused upstream artefact(s) are absent."
        )
    metadata = json.loads(
        (experiment_root / "model" / "model_stage_metadata.json").read_text(encoding="utf-8")
    )
    compare_metadata = json.loads(
        (experiment_root / "compare" / "compare_stage_metadata.json").read_text(encoding="utf-8")
    )
    materialization = {
        "probe_root": str(probe_root),
        "experiment_root": str(experiment_root),
        "reused_stages": list(REUSED_FROZEN_STAGES),
        "reused_artifact_count": len(present),
        "reused_artifact_bytes": sum(
            (experiment_root / rel).stat().st_size for rel in present
        ),
        "excluded_frozen_artifact_count": len(excluded),
        "excluded_frozen_artifacts": excluded,
        "recomputed_stages": list(RECOMPUTED_STAGES),
        "gee_queries_run": False,
        "gee_exports_run": False,
        "summarized_from": "existing probe namespace (--report-only)",
    }
    recomputation = {
        "analysis_id": metadata.get("analysis_id"),
        "experiment_id": metadata.get("experiment_id"),
        "model_fit": bool(metadata.get("model_fit")),
        "bootstrap_run": bool(metadata.get("bootstrap_run")),
        "model_evaluation_count": metadata.get("model_evaluation_count"),
        "model_files_written": len(metadata.get("artifact_inventory") or []),
        "compare_files_written": len(compare_metadata.get("output_artifacts") or []),
        "model_reused": False,
        "compare_reused": False,
        "model_configuration": metadata.get("model_configuration"),
        "gee_queries_run": False,
        "gee_exports_run": False,
        "summarized_from": "existing probe namespace (--report-only)",
    }
    return materialization, recomputation


# =============================================================================
# Old vs fresh comparison
# =============================================================================
def _model_tables(root: Path) -> dict[str, Any]:
    """The scientific tables of one `model/`+`compare/` tree."""
    import pandas as pd

    root = Path(root)
    frames = [
        pd.read_parquet(path)
        for path in sorted((root / "model" / "variants").glob("*/*/oof_predictions.parquet"))
    ]
    return {
        "point_metrics": pd.read_csv(root / "model" / "metrics" / "point_metrics.csv"),
        "thermal_contributions": pd.read_csv(
            root / "model" / "metrics" / "thermal_contributions.csv"
        ),
        "bootstrap_summary": pd.read_csv(
            root / "model" / "bootstrap" / "paired_bootstrap_summary.csv"
        ),
        "bootstrap_replicates": pd.read_parquet(
            root / "model" / "bootstrap" / "paired_bootstrap_replicates.parquet"
        ),
        "oof": pd.concat(frames, ignore_index=True),
        "folds": pd.read_parquet(
            root / "model" / "shared_folds" / "shared_spatial_folds.parquet"
        ),
        "cohort_metadata": json.loads(
            (root / "model" / "common_cohort" / "common_cohort_metadata.json")
            .read_text(encoding="utf-8")
        ),
        "cohort": pd.read_parquet(root / "model" / "common_cohort" / "common_cohort.parquet"),
    }


def compare_cohort_and_folds(old: Mapping[str, Any], new: Mapping[str, Any]) -> dict[str, Any]:
    """Population, labels, fold ids and spatial block ids (probe section 4A)."""
    rows: list[dict[str, Any]] = []

    def add(field: str, a: Any, b: Any) -> None:
        rows.append({"field": field, "old": a, "new": b, "equal": a == b})

    old_meta, new_meta = old["cohort_metadata"], new["cohort_metadata"]
    for field in (
        "final_common_cohort_rows", "final_positive_rows", "final_negative_rows",
        "removed_label_mismatch", "removed_static_invariance_failure",
        "primary_population",
    ):
        add(f"cohort.{field}", old_meta[field], new_meta[field])
    for field in (
        "initial_rows_by_variant", "removed_not_valid_for_modeling",
        "removed_outside_primary_population", "removed_prelabel_censor",
        "removed_missing_required_feature_union", "removed_variant_only_keys",
        "input_dataset_sha256", "required_feature_union",
    ):
        add(f"cohort.{field}", old_meta[field], new_meta[field])
    add("cohort.rows", len(old["cohort"]), len(new["cohort"]))
    add("cohort.cell_ids", list(old["cohort"]["cell_id"]) == list(new["cohort"]["cell_id"]), True)
    add("cohort.labels", list(old["cohort"]["burned"]) == list(new["cohort"]["burned"]), True)

    old_folds = old["folds"].set_index("cell_id")
    new_folds = new["folds"].set_index("cell_id")
    parts = [
        _numeric_diffs("fold_id", old_folds["fold_id"].astype(float).to_dict(),
                       new_folds["fold_id"].astype(float).to_dict()),
        _numeric_diffs("spatial_block_id", old_folds["spatial_block_id"].astype(float).to_dict(),
                       new_folds["spatial_block_id"].astype(float).to_dict()),
    ]
    unequal = [r for r in rows if not r["equal"]]
    equivalent = not unequal and all(p["equivalent"] for p in parts)
    return {
        "comparison": "cohort_and_folds", "rows": rows,
        "fields_compared": len(rows), "unequal_fields": unequal,
        "fold_parts": parts,
        "classification": CLASS_SCIENTIFIC if equivalent else CLASS_MATERIAL,
        "equivalent": equivalent,
    }


def compare_oof(old: Mapping[str, Any], new: Mapping[str, Any]) -> dict[str, Any]:
    """Row-key-aligned y_true / fold_id / y_score over every OOF row."""
    old_keyed = old["oof"].set_index(["variant_id", "model_family", "cell_id"])
    new_keyed = new["oof"].set_index(["variant_id", "model_family", "cell_id"])
    parts = [
        _numeric_diffs("y_score", old_keyed["y_score"].to_dict(), new_keyed["y_score"].to_dict()),
        _numeric_diffs("y_true", old_keyed["y_true"].astype(float).to_dict(),
                       new_keyed["y_true"].astype(float).to_dict()),
        _numeric_diffs("fold_id", old_keyed["fold_id"].astype(float).to_dict(),
                       new_keyed["fold_id"].astype(float).to_dict()),
        _numeric_diffs("spatial_block_id", old_keyed["spatial_block_id"].astype(float).to_dict(),
                       new_keyed["spatial_block_id"].astype(float).to_dict()),
    ]
    equivalent = all(p["equivalent"] for p in parts) and len(old["oof"]) == len(new["oof"])
    return {
        "comparison": "oof_predictions",
        "old_rows": int(len(old["oof"])), "new_rows": int(len(new["oof"])),
        "parts": parts,
        "classification": (
            CLASS_SCIENTIFIC if equivalent and all(
                p["differing_values"] == 0 for p in parts
            ) else CLASS_FLOAT if equivalent else CLASS_MATERIAL
        ),
        "equivalent": equivalent,
    }


def compare_metrics(old: Mapping[str, Any], new: Mapping[str, Any]) -> dict[str, Any]:
    """ROC-AUC / PR-AUC / Brier per variant x model, plus thermal contributions."""
    # `thermal_contributions.csv` is keyed by (variant_id, metric) and carries
    # the two levels plus their difference. Its `delta_definition` /
    # `sign_convention` columns are prose, so the numeric columns are named
    # explicitly rather than matched by prefix.
    contribution_columns = ("baseline", "thermal", "contribution_delta")
    old_values: dict[str, float] = {}
    new_values: dict[str, float] = {}
    for table, target in ((old, old_values), (new, new_values)):
        for _, row in table["point_metrics"].iterrows():
            for metric in ("roc_auc", "pr_auc", "brier"):
                target[f"{row['variant_id']}|{row['model_family']}|{metric}"] = float(row[metric])
        for _, row in table["thermal_contributions"].iterrows():
            for column in contribution_columns:
                target[
                    f"contribution|{row['variant_id']}|{row['metric']}|{column}"
                ] = float(row[column])
    result = _numeric_diffs("point_metrics_and_contributions", old_values, new_values)
    result["side_by_side"] = [
        {"key": key, "old": old_values[key], "new": new_values.get(key),
         "abs_diff": abs(new_values[key] - old_values[key]) if key in new_values else None}
        for key in sorted(old_values)
    ]
    return result


def compare_bootstrap(old: Mapping[str, Any], new: Mapping[str, Any]) -> dict[str, Any]:
    """27 summary series and all 27,000 replicate draws."""
    old_values: dict[str, float] = {}
    new_values: dict[str, float] = {}
    for table, target in ((old, old_values), (new, new_values)):
        for _, row in table["bootstrap_summary"].iterrows():
            stem = (f"{row['comparison']}|{row['variant_id']}|"
                    f"{row['model_family']}|{row['metric']}")
            for column in ("point_delta", "ci_low", "ci_high", "bootstrap_mean",
                           "valid_replicates", "invalid_replicates", "block_count",
                           "bootstrap_seed", "requested_replicates"):
                target[f"{stem}|{column}"] = float(row[column])
    summary = _numeric_diffs("bootstrap_summary", old_values, new_values)

    old_reps, new_reps = old["bootstrap_replicates"], new["bootstrap_replicates"]
    columns = sorted(set(old_reps.columns) & set(new_reps.columns))
    old_draws: dict[str, float] = {}
    new_draws: dict[str, float] = {}
    for column in columns:
        for index, value in enumerate(old_reps[column].tolist()):
            old_draws[f"{column}|{index}"] = float(value)
        for index, value in enumerate(new_reps[column].tolist()):
            new_draws[f"{column}|{index}"] = float(value)
    replicates = _numeric_diffs("bootstrap_replicates", old_draws, new_draws)
    replicates["old_columns"] = sorted(old_reps.columns)
    replicates["new_columns"] = sorted(new_reps.columns)
    replicates["columns_equal"] = sorted(old_reps.columns) == sorted(new_reps.columns)
    replicates["old_draws"] = int(len(old_reps))
    replicates["new_draws"] = int(len(new_reps))
    equivalent = (
        summary["equivalent"] and replicates["equivalent"]
        and replicates["columns_equal"] and len(old_reps) == len(new_reps)
    )
    return {
        "comparison": "bootstrap",
        "summary": summary, "replicates": replicates,
        "series_count_old": int(len(old["bootstrap_summary"])),
        "series_count_new": int(len(new["bootstrap_summary"])),
        "classification": CLASS_SCIENTIFIC if equivalent else CLASS_MATERIAL,
        "equivalent": equivalent,
    }


def compare_compare_tables(old_root: Path, new_root: Path) -> dict[str, Any]:
    """The regenerated comparison tables, column by column.

    A whole-frame equality test would report a last-ULP difference in one
    numeric column as a wholesale table mismatch, so every column is compared on
    its own terms: numeric columns by magnitude of difference, everything else
    (labels, definitions, sign conventions, interval statuses) by exact
    equality. A changed word is therefore still a material difference.
    """
    import pandas as pd

    old_root, new_root = Path(old_root), Path(new_root)
    tables = sorted(p.name for p in (old_root / "compare" / "tables").glob("*.csv"))
    records: list[dict[str, Any]] = []
    for name in tables:
        old_path = old_root / "compare" / "tables" / name
        new_path = new_root / "compare" / "tables" / name
        if not new_path.is_file():
            records.append({
                "table": name, "present": False, "equal": False,
                "byte_identical": False, "classification": CLASS_MATERIAL,
            })
            continue
        old_frame = pd.read_csv(old_path)
        new_frame = pd.read_csv(new_path)
        same_shape = old_frame.shape == new_frame.shape
        same_columns = list(old_frame.columns) == list(new_frame.columns)
        numeric_max = 0.0
        numeric_differing = 0
        text_mismatches: list[str] = []
        if same_shape and same_columns:
            for column in old_frame.columns:
                old_column, new_column = old_frame[column], new_frame[column]
                if old_column.equals(new_column):
                    continue
                numeric = (
                    pd.api.types.is_numeric_dtype(old_column)
                    and pd.api.types.is_numeric_dtype(new_column)
                )
                if numeric:
                    delta = (old_column.astype(float) - new_column.astype(float)).abs()
                    numeric_max = max(numeric_max, float(delta.max()))
                    numeric_differing += int((delta > 0).sum())
                else:
                    text_mismatches.append(column)
        structural_ok = same_shape and same_columns
        within_tolerance = numeric_max <= FLOAT_SERIALIZATION_TOLERANCE
        equal = bool(
            structural_ok and not text_mismatches and numeric_differing == 0
        )
        equivalent = bool(structural_ok and not text_mismatches and within_tolerance)
        records.append({
            "table": name, "present": True, "old_shape": list(old_frame.shape),
            "new_shape": list(new_frame.shape), "columns_equal": same_columns,
            "equal": equal, "equivalent": equivalent,
            "numeric_max_abs_diff": numeric_max,
            "numeric_differing_values": numeric_differing,
            "non_numeric_mismatched_columns": text_mismatches,
            "byte_identical": sha256_path(old_path) == sha256_path(new_path),
            "classification": (
                CLASS_SCIENTIFIC if equal
                else CLASS_FLOAT if equivalent else CLASS_MATERIAL
            ),
        })
    report_old = old_root / "compare" / "report" / "window_closure_comparison.md"
    report_new = new_root / "compare" / "report" / "window_closure_comparison.md"
    report_identical = (
        report_new.is_file() and sha256_path(report_old) == sha256_path(report_new)
    )
    material = [r for r in records if r["classification"] == CLASS_MATERIAL]
    float_only = [r for r in records if r["classification"] == CLASS_FLOAT]
    return {
        "comparison": "compare_tables",
        "tables": records, "table_count": len(records),
        "byte_identical_tables": sum(1 for r in records if r.get("byte_identical")),
        "exactly_equal_tables": sum(1 for r in records if r.get("equal")),
        "float_equivalent_tables": len(float_only),
        "material_difference_tables": material,
        "max_abs_diff": max((r.get("numeric_max_abs_diff", 0.0) for r in records), default=0.0),
        "report_byte_identical": report_identical,
        "classification": (
            CLASS_MATERIAL if material
            else CLASS_FLOAT if float_only else CLASS_SCIENTIFIC
        ),
        "equivalent": not material,
    }


# =============================================================================
# The determinism control -- why exact bit reproduction is impossible here
# =============================================================================
def threaded_prediction_control(probe_experiment_root: Path, *, repeats: int = 5) -> dict[str, Any]:
    """Measure sklearn's own run-to-run `predict_proba` nondeterminism.

    The production classifier is
    ``RandomForestClassifier(..., random_state=seed, n_jobs=-1)``
    (`src/step8b_train_baseline_vs_thermal_model.py:420-429`). With `n_jobs=-1`
    scikit-learn accumulates the per-tree probabilities into a shared array from
    several threads, and floating-point addition is not associative, so the
    order in which trees land changes the last bits of the average.

    This control fits ONE production-configured forest on the probe's own
    cohort and calls `predict_proba` repeatedly. If repeated calls on a SINGLE
    fitted forest already differ by the same magnitude as old-vs-fresh, then
    that magnitude is a property of the estimator configuration and not
    evidence that the two runs computed different science. The fitted tree
    structures are compared across two independent fits to show the forest
    itself is deterministic.
    """
    import numpy as np
    import pandas as pd

    from src.step8b_train_baseline_vs_thermal_model import BASELINE_FEATURES, build_pipeline

    root = Path(probe_experiment_root)
    cohort = pd.read_parquet(root / "model" / "common_cohort" / "common_cohort.parquet")
    folds = pd.read_parquet(root / "model" / "shared_folds" / "shared_spatial_folds.parquet")
    frame = cohort.drop(columns=[c for c in ("fold_id", "spatial_block_id") if c in cohort.columns])
    frame = frame.merge(folds[["cell_id", "fold_id"]], on="cell_id")
    train = frame[frame["fold_id"] != 0]
    test = frame[frame["fold_id"] == 0]
    features = list(BASELINE_FEATURES)

    pipeline = build_pipeline(features, "random_forest", 42)
    pipeline.fit(train[features], train["burned"].astype(int))
    threaded = [pipeline.predict_proba(test[features])[:, 1] for _ in range(repeats)]
    threaded_deltas = [float(np.abs(run - threaded[0]).max()) for run in threaded[1:]]
    threaded_differing = [int((np.abs(run - threaded[0]) > 0).sum()) for run in threaded[1:]]

    classifier = pipeline.named_steps["clf"]
    configured_n_jobs = classifier.n_jobs
    classifier.n_jobs = 1
    serial = [pipeline.predict_proba(test[features])[:, 1] for _ in range(3)]
    serial_deltas = [float(np.abs(run - serial[0]).max()) for run in serial[1:]]
    classifier.n_jobs = configured_n_jobs

    second = build_pipeline(features, "random_forest", 42)
    second.fit(train[features], train["burned"].astype(int))
    trees_identical = all(
        np.array_equal(a.tree_.feature, b.tree_.feature)
        and np.array_equal(a.tree_.threshold, b.tree_.threshold)
        and np.array_equal(a.tree_.value, b.tree_.value)
        for a, b in zip(classifier.estimators_, second.named_steps["clf"].estimators_)
    )
    import sklearn
    return {
        "control": "threaded_predict_proba_nondeterminism",
        "estimator": "RandomForestClassifier",
        "configured_n_jobs": configured_n_jobs,
        "n_estimators": int(classifier.n_estimators),
        "random_state": int(classifier.random_state),
        "rows_scored": int(len(test)),
        "threaded_repeat_max_abs_diffs": threaded_deltas,
        "threaded_repeat_differing_counts": threaded_differing,
        "threaded_is_bit_reproducible": all(d == 0.0 for d in threaded_deltas),
        "serial_repeat_max_abs_diffs": serial_deltas,
        "serial_is_bit_reproducible": all(d == 0.0 for d in serial_deltas),
        "fitted_trees_identical_across_independent_fits": bool(trees_identical),
        "tree_count_compared": int(len(classifier.estimators_)),
        "sklearn_version": sklearn.__version__,
        "conclusion": (
            "The fitted forest is deterministic; only the threaded averaging in "
            "predict_proba is not. Exact bit-for-bit reproduction of the frozen "
            "scores is impossible under the frozen n_jobs=-1 configuration, and "
            "the observed old-vs-fresh magnitude matches this estimator's own "
            "run-to-run variation."
        ),
    }


def compare_model_artifact_hashes(old_root: Path, new_root: Path) -> dict[str, Any]:
    """Byte identity of the model/ artefacts. Reported, never a PASS criterion."""
    old_root, new_root = Path(old_root), Path(new_root)
    records: list[dict[str, Any]] = []
    for path in sorted((old_root / "model").rglob("*")):
        if not path.is_file() or EXCLUDED_TREE_COMPONENT in path.parts:
            continue
        relative = path.relative_to(old_root)
        candidate = new_root / relative
        records.append({
            "relative_path": str(relative),
            "present_in_probe": candidate.is_file(),
            "byte_identical": (
                candidate.is_file() and sha256_path(path) == sha256_path(candidate)
            ),
        })
    identical = sum(1 for r in records if r["byte_identical"])
    return {
        "comparison": "model_artifact_bytes",
        "artifact_count": len(records), "byte_identical": identical,
        "not_byte_identical": [r["relative_path"] for r in records if not r["byte_identical"]],
        "records": records,
        "is_pass_criterion": False,
        "note": (
            "Serialization (parquet metadata, JSON key order, embedded paths and "
            "timestamps) may legitimately differ. Scientific equivalence is "
            "established by predictions, folds, metrics and bootstrap results."
        ),
    }


# =============================================================================
# Three-way chain: old frozen vs regional replay vs fresh recomputation
# =============================================================================
def _three_way_verdict(
    label: str,
    old_values: Mapping[str, float],
    replay_values: Mapping[str, float],
    fresh_values: Mapping[str, float],
) -> dict[str, Any]:
    """Chain verdict with the right expectation on each leg.

    The regional replay REUSES the frozen artefacts, so its leg must be exactly
    equal -- any difference there is a wrapper defect. The fresh leg refits, so
    it is held to machine-level equivalence instead, because the production
    estimator is not bit-reproducible (see `threaded_prediction_control`).
    """
    keys = sorted(old_values)
    rows: list[dict[str, Any]] = []
    replay_exact = bool(replay_values)
    fresh_max = 0.0
    for key in keys:
        old = old_values[key]
        replay = replay_values.get(key)
        fresh = fresh_values.get(key)
        replay_ok = replay == old
        if not replay_ok:
            replay_exact = False
        fresh_delta = abs(fresh - old) if fresh is not None else None
        if fresh_delta is not None:
            fresh_max = max(fresh_max, fresh_delta)
        rows.append({
            "key": key, "old_frozen": old, "regional_replay": replay,
            "fresh_recomputation": fresh,
            "replay_exactly_equal": replay_ok,
            "fresh_abs_diff": fresh_delta,
            "all_equal": old == replay == fresh,
        })
    fresh_equivalent = (
        all(r["fresh_recomputation"] is not None for r in rows)
        and fresh_max <= FLOAT_SERIALIZATION_TOLERANCE
    )
    return {
        "comparison": label,
        "replay_available": bool(replay_values),
        "values_compared": len(rows),
        "exactly_equal_across_all_three": sum(1 for r in rows if r["all_equal"]),
        "old_vs_replay_exactly_equal": replay_exact,
        "fresh_max_abs_diff": fresh_max,
        "fresh_within_machine_tolerance": fresh_equivalent,
        "all_three_equal": all(r["all_equal"] for r in rows) and bool(replay_values),
        "all_three_equivalent": bool(replay_exact and fresh_equivalent),
        "rows": rows,
        "disagreements": [r for r in rows if not r["all_equal"]],
    }


def three_way_headline(
    old_root: Path, replay_root: Optional[Path], probe_experiment_root: Path,
) -> dict[str, Any]:
    """The same 18 headline values read from all three trees."""
    import pandas as pd

    def from_point_metrics(root: Path) -> dict[str, float]:
        frame = pd.read_csv(Path(root) / "model" / "metrics" / "point_metrics.csv")
        return {
            f"{row['variant_id']}|{row['model_family']}|{metric}": float(row[metric])
            for _, row in frame.iterrows()
            for metric in ("roc_auc", "pr_auc", "brier")
        }

    old_values = from_point_metrics(old_root)
    fresh_values = from_point_metrics(probe_experiment_root)
    replay_values: dict[str, float] = {}
    if replay_root is not None and (Path(replay_root) / "metrics.csv").is_file():
        frame = pd.read_csv(Path(replay_root) / "metrics.csv")
        replay_values = {
            f"{row['variant']}|{row['model']}|{row['metric']}": float(row["estimate"])
            for _, row in frame.iterrows()
        }
    return _three_way_verdict(
        "three_way_headline_metrics", old_values, replay_values, fresh_values,
    )


def three_way_bootstrap(
    old_root: Path, replay_root: Optional[Path], probe_experiment_root: Path,
) -> dict[str, Any]:
    """The 27 bootstrap series point estimate and CI bounds, in all three trees."""
    import pandas as pd

    def from_frozen(root: Path) -> dict[str, float]:
        frame = pd.read_csv(
            Path(root) / "model" / "bootstrap" / "paired_bootstrap_summary.csv"
        )
        out: dict[str, float] = {}
        for _, row in frame.iterrows():
            stem = (f"{row['comparison']}|{row['variant_id']}|"
                    f"{row['model_family']}|{row['metric']}")
            out[f"{stem}|point"] = float(row["point_delta"])
            out[f"{stem}|ci_low"] = float(row["ci_low"])
            out[f"{stem}|ci_high"] = float(row["ci_high"])
        return out

    old_values = from_frozen(old_root)
    fresh_values = from_frozen(probe_experiment_root)
    replay_values: dict[str, float] = {}
    if replay_root is not None and (Path(replay_root) / "bootstrap_summary.csv").is_file():
        frame = pd.read_csv(Path(replay_root) / "bootstrap_summary.csv")
        for _, row in frame.iterrows():
            stem = (f"{row['comparison']}|{row['variant_id']}|"
                    f"{row['model_family']}|{row['metric']}")
            replay_values[f"{stem}|point"] = float(row["point_estimate_natural"])
            replay_values[f"{stem}|ci_low"] = float(row["ci_low_natural"])
            replay_values[f"{stem}|ci_high"] = float(row["ci_high_natural"])
    return _three_way_verdict(
        "three_way_bootstrap_summary", old_values, replay_values, fresh_values,
    )


# =============================================================================
# Report
# =============================================================================
def build_probe_report(
    *, frozen_source: Path, probe_root: Path, replay_root: Optional[Path],
    preflight: Mapping[str, Any], materialization: Mapping[str, Any],
    recomputation: Mapping[str, Any], mutation_guard: Mapping[str, Any],
) -> dict[str, Any]:
    frozen_source, probe_root = Path(frozen_source), Path(probe_root)
    probe_experiment_root = probe_root / REFERENCE_AOI
    old = _model_tables(frozen_source)
    new = _model_tables(probe_experiment_root)
    sections = {
        "contract": {
            "comparison": "scientific_contract",
            "scientific_fields_compared": preflight["scientific_field_count"],
            "mismatches": preflight["mismatches"],
            "non_scientific_differences": [
                {"field": c["field"], "old": c["old"], "new": c["new"]}
                for c in preflight["non_scientific_differences"]
            ],
            "classification": CLASS_SCIENTIFIC if not preflight["mismatches"] else CLASS_MATERIAL,
            "equivalent": not preflight["mismatches"],
        },
        "cohort_and_folds": compare_cohort_and_folds(old, new),
        "oof_predictions": compare_oof(old, new),
        "metrics": compare_metrics(old, new),
        "bootstrap": compare_bootstrap(old, new),
        "compare_tables": compare_compare_tables(frozen_source, probe_experiment_root),
        "model_artifact_bytes": compare_model_artifact_hashes(
            frozen_source, probe_experiment_root,
        ),
    }
    three_way = {
        "headline_metrics": three_way_headline(frozen_source, replay_root, probe_experiment_root),
        "bootstrap_summary": three_way_bootstrap(frozen_source, replay_root, probe_experiment_root),
    }
    control = threaded_prediction_control(probe_experiment_root)
    scored = [
        name for name in
        ("contract", "cohort_and_folds", "oof_predictions", "metrics", "bootstrap",
         "compare_tables")
    ]
    numeric_max = max([
        float(sections["metrics"].get("max_abs_diff", 0.0)),
        float(sections["bootstrap"]["summary"].get("max_abs_diff", 0.0)),
        float(sections["bootstrap"]["replicates"].get("max_abs_diff", 0.0)),
        max((float(p.get("max_abs_diff", 0.0)) for p in sections["oof_predictions"]["parts"]),
            default=0.0),
        max((float(p.get("max_abs_diff", 0.0)) for p in sections["cohort_and_folds"]["fold_parts"]),
            default=0.0),
    ])
    all_equivalent = all(bool(sections[name]["equivalent"]) for name in scored)
    exact = numeric_max == 0.0
    sources_unchanged = bool(mutation_guard.get("all_unchanged"))
    really_recomputed = (
        bool(recomputation["model_fit"]) and bool(recomputation["bootstrap_run"])
        and not recomputation["model_reused"] and not recomputation["compare_reused"]
    )
    verdict = "PASS" if (
        preflight["status"] == "PASS" and all_equivalent and sources_unchanged
        and really_recomputed
    ) else "FAIL"
    return {
        "schema_version": "window_closure_local_recomputation_probe.v1",
        "probe_mode": PROBE_MODE_ID,
        "aoi": REFERENCE_AOI,
        "old_source_path": str(frozen_source),
        "probe_path": str(probe_root),
        "probe_experiment_root": str(probe_experiment_root),
        "regional_replay_path": str(replay_root) if replay_root else None,
        "probe_analysis_id": recomputation["analysis_id"],
        "materialization": {
            key: value for key, value in materialization.items()
            if key not in ("reused_artifacts", "excluded_frozen_artifacts")
        },
        "excluded_frozen_artifacts": materialization["excluded_frozen_artifacts"],
        "recomputation": recomputation,
        "sections": sections,
        "three_way": three_way,
        "determinism_control": control,
        "max_numeric_abs_diff": numeric_max,
        "exact_bit_for_bit": exact,
        "float_tolerance_used": FLOAT_SERIALIZATION_TOLERANCE,
        "tolerance_needed": not exact,
        "difference_cause": (
            "none -- every compared value is exactly equal" if exact else
            "scikit-learn's threaded RandomForest predict_proba accumulation "
            "(n_jobs=-1). Demonstrated by `determinism_control`: repeated "
            "predict_proba calls on ONE fitted forest vary by the same "
            "magnitude, while n_jobs=1 is bit-reproducible and the fitted tree "
            "structures are identical across independent same-seed fits."
        ),
        "difference_is_machine_level": (
            exact or numeric_max <= max(
                (control["threaded_repeat_max_abs_diffs"] or [0.0])
            ) * 4 or numeric_max <= 1e-13
        ),
        "source_mutation_guard": mutation_guard,
        "gee_queries_run": False,
        "gee_exports_run": False,
        "remote_downloads": 0,
        "determinism_verdict": (
            "STRONG_DETERMINISM_PASS_BIT_EXACT" if verdict == "PASS" and exact
            else "STRONG_DETERMINISM_PASS_MACHINE_EPSILON" if verdict == "PASS"
            else "FAIL"
        ),
        "equivalence_verdict": verdict,
        "safe_to_retire_old_physical_layout": (
            verdict == "PASS"
            and three_way["headline_metrics"]["all_three_equivalent"]
            and three_way["bootstrap_summary"]["all_three_equivalent"]
        ),
        "migration_performed": False,
        "note": (
            "This turn produces determinism evidence only. Nothing under the "
            "frozen Manavgat namespace, the regional replay namespace or the "
            "four production regional namespaces was written, moved, renamed "
            "or deleted."
        ),
    }


def probe_guarded_trees(output_root: Optional[Path] = None) -> dict[str, tuple[Path, tuple[str, ...]]]:
    """The frozen tree, the four production regional trees, AND the replay tree."""
    from src.multi_region_window_closure.reference_replay import (
        REGIONAL_CRITICAL_FILES, guarded_trees,
    )

    trees = dict(guarded_trees(output_root))
    replay = replay_namespace_root()
    if replay is not None:
        trees[f"replay/{REFERENCE_AOI}/{replay.name}"] = (replay, REGIONAL_CRITICAL_FILES)
    return trees


def snapshot_probe_guarded_trees(output_root: Optional[Path] = None) -> dict[str, Any]:
    return {
        name: tree_snapshot(path, critical)
        for name, (path, critical) in probe_guarded_trees(output_root).items()
    }


def render_probe_report(report: Mapping[str, Any]) -> str:
    sections = report["sections"]
    lines = [
        "# Manavgat local recomputation determinism probe",
        "",
        f"**Determinism verdict: {report['determinism_verdict']}**",
        "",
        f"- AOI: `{report['aoi']}`",
        f"- Old frozen source: `{report['old_source_path']}`",
        f"- Probe namespace: `{report['probe_experiment_root']}`",
        f"- Regional replay: `{report['regional_replay_path']}`",
        f"- Probe analysis id: `{report['probe_analysis_id']}`",
        f"- Earth Engine queries / exports / downloads: "
        f"{report['gee_queries_run']} / {report['gee_exports_run']} / {report['remote_downloads']}",
        "",
        "## What was recomputed vs reused",
        "",
        f"- Recomputed stages: {report['recomputation']['model_evaluation_count']} model "
        f"evaluations, model_fit={report['recomputation']['model_fit']}, "
        f"bootstrap_run={report['recomputation']['bootstrap_run']}",
        f"- Reused upstream artefacts: "
        f"{report['materialization']['reused_artifact_count']} files "
        f"({report['materialization']['reused_artifact_bytes']} bytes)",
        f"- Frozen artefacts deliberately NOT copied: "
        f"{report['materialization']['excluded_frozen_artifact_count']}",
        "",
        "## Section results",
        "",
        "| Section | Classification | Equivalent |",
        "| --- | --- | --- |",
    ]
    for name, section in sections.items():
        lines.append(
            f"| {name} | {section.get('classification', '-')} | "
            f"{'yes' if section.get('equivalent', True) else 'NO'} |"
        )
    lines += [
        "",
        "## Numeric differences",
        "",
        f"- Max absolute difference over every compared scientific value: "
        f"`{report['max_numeric_abs_diff']}`",
        f"- Exact bit-for-bit: **{report['exact_bit_for_bit']}**",
        f"- Difference is machine-level: {report['difference_is_machine_level']}",
        f"- Cause: {report['difference_cause']}",
        "",
        "## Determinism control",
        "",
        f"- Estimator: {report['determinism_control']['estimator']} "
        f"(n_estimators={report['determinism_control']['n_estimators']}, "
        f"random_state={report['determinism_control']['random_state']}, "
        f"n_jobs={report['determinism_control']['configured_n_jobs']})",
        f"- Repeated `predict_proba` on ONE fitted forest is bit-reproducible: "
        f"**{report['determinism_control']['threaded_is_bit_reproducible']}** "
        f"(max abs diffs {report['determinism_control']['threaded_repeat_max_abs_diffs']})",
        f"- With `n_jobs=1` it is bit-reproducible: "
        f"**{report['determinism_control']['serial_is_bit_reproducible']}**",
        f"- Fitted tree structures identical across two independent same-seed fits: "
        f"**{report['determinism_control']['fitted_trees_identical_across_independent_fits']}** "
        f"({report['determinism_control']['tree_count_compared']} trees)",
        "",
        "## Three-way equality (old frozen / regional replay / fresh recomputation)",
        "",
        "| Chain | values | exact across all three | old vs replay exact | "
        "fresh max abs diff | equivalent |",
        "| --- | --- | --- | --- | --- | --- |",
        *[
            f"| {name} | {s['values_compared']} | "
            f"{s['exactly_equal_across_all_three']} | "
            f"{s['old_vs_replay_exactly_equal']} | {s['fresh_max_abs_diff']} | "
            f"{s['all_three_equivalent']} |"
            for name, s in report["three_way"].items()
        ],
        "",
        "## Model artefact bytes (reported, not a PASS criterion)",
        "",
        f"- Byte-identical: {sections['model_artifact_bytes']['byte_identical']} of "
        f"{sections['model_artifact_bytes']['artifact_count']}",
        "",
        "## Source mutation guard",
        "",
        f"- Trees checked: {len(report['source_mutation_guard']['trees_checked'])}",
        f"- All unchanged: "
        f"{'yes' if report['source_mutation_guard']['all_unchanged'] else 'NO'}",
        "",
        report["note"],
        "",
    ]
    return "\n".join(lines)
